apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app-v19
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: app-site
        image: mtituana/angular-app:v${BUILD_NUMBER}
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: app-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
